### ISSUE TITLE
Locale translation

### ISSUE THREAD

**Issue by Qyuriz** [MystenLabs/move-book#96]
Hello there, i come from Indonesia. Is there any possibility to make a contribution for the move book? i want to translate this to my locale.

**Comment by Qyuriz** [comment]
Thank you, i will dot it ASAP

**Comment by Qyuriz** [comment]
Forked it, if I finish the translation, will open a new issue in the future.

**Comment by damirka** [comment]
Hey @Qyuriz I'm closing the issue as completed. Feel free to open a new one when ready!
